export type Vehicle = {
  id: string;
  year: number;
  make: string;
  model: string;
  trim: string;
  price: number;
  mileage: number;
  bodyStyle:
    | "SUV"
    | "Sedan"
    | "Truck"
    | "Coupe"
    | "Hatchback"
    | "Minivan"
    | "Cargo Van"
    | "Passenger Van"
    | "Wagon"
    | "Convertible";
  drivetrain: "AWD" | "FWD" | "RWD" | "4WD";
  transmission: string;
  fuel: "Gasoline" | "Hybrid" | "Electric";
  exteriorColor: string;
  mpg: string;
  image: string;
  tag?: "Certified" | "New Arrival" | "Price Drop" | "Low Miles";
  /**
   * Additive classifiers that are not body styles. Used by the vehicle
   * category landing pages for the commercial / former-police / luxury feeds.
   */
  commercial?: boolean;
  formerPolice?: boolean;
  luxury?: boolean;
};

/**
 * Photography: Unsplash source URLs. Next.js optimizes these (resize + WebP)
 * per the `remotePatterns` allow-list in next.config.ts.
 */
const IMG = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=70`;

/** Pexels CDN photo by id (allow-listed in next.config.ts). */
const PEX = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=1400`;

export const VEHICLES: Vehicle[] = [
  {
    id: "bcc-2019-honda-crv",
    year: 2019,
    make: "Honda",
    model: "CR-V",
    trim: "EX AWD",
    price: 21995,
    mileage: 58120,
    bodyStyle: "SUV",
    drivetrain: "AWD",
    transmission: "CVT",
    fuel: "Gasoline",
    exteriorColor: "Platinum White Pearl",
    mpg: "27 city / 32 hwy",
    image: IMG("photo-1519641471654-76ce0107ad1b"),
    tag: "Certified",
  },
  {
    id: "bcc-2020-toyota-camry",
    year: 2020,
    make: "Toyota",
    model: "Camry",
    trim: "LE",
    price: 19450,
    mileage: 43870,
    bodyStyle: "Sedan",
    drivetrain: "FWD",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Predawn Gray Mica",
    mpg: "28 city / 39 hwy",
    image: IMG("photo-1621007947382-bb3c3994e3fb"),
    tag: "New Arrival",
  },
  {
    id: "bcc-2018-toyota-corolla",
    year: 2018,
    make: "Toyota",
    model: "Corolla",
    trim: "LE",
    price: 15995,
    mileage: 61540,
    bodyStyle: "Sedan",
    drivetrain: "FWD",
    transmission: "CVT",
    fuel: "Gasoline",
    exteriorColor: "Super White",
    mpg: "30 city / 40 hwy",
    image: IMG("photo-1638618164682-12b986ec2a75"),
    tag: "Price Drop",
  },
  {
    id: "bcc-2021-toyota-4runner",
    year: 2021,
    make: "Toyota",
    model: "4Runner",
    trim: "SR5 4x4",
    price: 34900,
    mileage: 38960,
    bodyStyle: "SUV",
    drivetrain: "4WD",
    transmission: "5-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Magnetic Gray Metallic",
    mpg: "16 city / 19 hwy",
    image: IMG("photo-1621993202323-f438eec934ff"),
    tag: "Low Miles",
  },
  {
    id: "bcc-2017-ford-f150",
    year: 2017,
    make: "Ford",
    model: "F-150",
    trim: "XLT SuperCrew 4x4",
    price: 23995,
    mileage: 78310,
    bodyStyle: "Truck",
    drivetrain: "4WD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Magnetic Gray",
    mpg: "18 city / 24 hwy",
    image: IMG("photo-1605893477799-b99e3b8b93fe"),
    tag: "Certified",
  },
  {
    id: "bcc-2020-ford-expedition",
    year: 2020,
    make: "Ford",
    model: "Expedition",
    trim: "XLT 4x4",
    price: 32500,
    mileage: 61780,
    bodyStyle: "SUV",
    drivetrain: "4WD",
    transmission: "10-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Oxford White",
    mpg: "17 city / 23 hwy",
    image: IMG("photo-1533473359331-0135ef1b58bf"),
  },
  {
    id: "bcc-2019-tesla-model-3",
    year: 2019,
    make: "Tesla",
    model: "Model 3",
    trim: "Standard Range Plus",
    price: 21900,
    mileage: 55230,
    bodyStyle: "Sedan",
    drivetrain: "RWD",
    transmission: "Single-Speed",
    fuel: "Electric",
    exteriorColor: "Pearl White Multi-Coat",
    mpg: "138 MPGe combined",
    image: IMG("photo-1560958089-b8a1929cea89"),
    tag: "New Arrival",
  },
  {
    id: "bcc-2020-audi-q5",
    year: 2020,
    make: "Audi",
    model: "Q5",
    trim: "Premium 45 TFSI quattro",
    price: 26900,
    mileage: 46110,
    bodyStyle: "SUV",
    drivetrain: "AWD",
    transmission: "7-Speed S tronic",
    fuel: "Gasoline",
    exteriorColor: "Glacier White Metallic",
    mpg: "22 city / 27 hwy",
    image: IMG("photo-1517524008697-84bbe3c3fd98"),
    tag: "Low Miles",
    luxury: true,
  },
  {
    id: "bcc-2020-hyundai-elantra",
    year: 2020,
    make: "Hyundai",
    model: "Elantra",
    trim: "SEL",
    price: 16450,
    mileage: 47690,
    bodyStyle: "Sedan",
    drivetrain: "FWD",
    transmission: "CVT",
    fuel: "Gasoline",
    exteriorColor: "Phantom Black",
    mpg: "31 city / 41 hwy",
    image: IMG("photo-1619767886558-efdc259cde1a"),
  },
  {
    id: "bcc-2019-hyundai-elantra-gt",
    year: 2019,
    make: "Hyundai",
    model: "Elantra GT",
    trim: "Hatchback",
    price: 14995,
    mileage: 52340,
    bodyStyle: "Hatchback",
    drivetrain: "FWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Scarlet Red Pearl",
    mpg: "24 city / 32 hwy",
    image: IMG("photo-1550355291-bbee04a92027"),
  },
  {
    id: "bcc-2017-nissan-juke",
    year: 2017,
    make: "Nissan",
    model: "Juke",
    trim: "SV",
    price: 11995,
    mileage: 71450,
    bodyStyle: "SUV",
    drivetrain: "FWD",
    transmission: "CVT",
    fuel: "Gasoline",
    exteriorColor: "Brilliant Silver",
    mpg: "28 city / 32 hwy",
    image: IMG("photo-1609521263047-f8f205293f24"),
  },
  {
    id: "bcc-2018-bmw-530i",
    year: 2018,
    make: "BMW",
    model: "530i",
    trim: "xDrive",
    price: 22500,
    mileage: 59870,
    bodyStyle: "Sedan",
    drivetrain: "AWD",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Jet Black",
    mpg: "24 city / 34 hwy",
    image: IMG("photo-1546614042-7df3c24c9e5d"),
    luxury: true,
  },
  {
    id: "bcc-2019-toyota-rav4",
    year: 2019,
    make: "Toyota",
    model: "RAV4",
    trim: "XLE AWD",
    price: 24900,
    mileage: 49300,
    bodyStyle: "SUV",
    drivetrain: "AWD",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Super White",
    mpg: "26 city / 35 hwy",
    image: PEX(17612417),
    tag: "Certified",
  },
  {
    id: "bcc-2018-honda-accord",
    year: 2018,
    make: "Honda",
    model: "Accord",
    trim: "Sport 1.5T",
    price: 18900,
    mileage: 62100,
    bodyStyle: "Sedan",
    drivetrain: "FWD",
    transmission: "CVT",
    fuel: "Gasoline",
    exteriorColor: "Modern Steel Metallic",
    mpg: "29 city / 35 hwy",
    image: PEX(5735089),
  },
  {
    id: "bcc-2021-subaru-forester",
    year: 2021,
    make: "Subaru",
    model: "Forester",
    trim: "Premium AWD",
    price: 26400,
    mileage: 33800,
    bodyStyle: "SUV",
    drivetrain: "AWD",
    transmission: "CVT",
    fuel: "Gasoline",
    exteriorColor: "Crystal Black Silica",
    mpg: "26 city / 33 hwy",
    image: PEX(14850138),
    tag: "Low Miles",
  },
  {
    id: "bcc-2017-nissan-altima",
    year: 2017,
    make: "Nissan",
    model: "Altima",
    trim: "2.5 SV",
    price: 13500,
    mileage: 88400,
    bodyStyle: "Sedan",
    drivetrain: "FWD",
    transmission: "CVT",
    fuel: "Gasoline",
    exteriorColor: "Cayenne Red",
    mpg: "27 city / 39 hwy",
    image: PEX(5864402),
  },
  {
    id: "bcc-2020-mazda-cx5",
    year: 2020,
    make: "Mazda",
    model: "CX-5",
    trim: "Touring AWD",
    price: 23950,
    mileage: 41200,
    bodyStyle: "SUV",
    drivetrain: "AWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Snowflake White Pearl",
    mpg: "24 city / 30 hwy",
    image: PEX(37141260),
    tag: "New Arrival",
  },
  {
    id: "bcc-2016-toyota-highlander",
    year: 2016,
    make: "Toyota",
    model: "Highlander",
    trim: "XLE AWD",
    price: 19900,
    mileage: 104600,
    bodyStyle: "SUV",
    drivetrain: "AWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Midnight Black Metallic",
    mpg: "19 city / 25 hwy",
    image: PEX(2920064),
  },
  {
    id: "bcc-2019-ford-escape",
    year: 2019,
    make: "Ford",
    model: "Escape",
    trim: "SE",
    price: 16400,
    mileage: 57900,
    bodyStyle: "SUV",
    drivetrain: "FWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Ruby Red Metallic",
    mpg: "23 city / 30 hwy",
    image: PEX(26572217),
  },
  {
    id: "bcc-2018-chevrolet-equinox",
    year: 2018,
    make: "Chevrolet",
    model: "Equinox",
    trim: "LT",
    price: 15900,
    mileage: 71300,
    bodyStyle: "SUV",
    drivetrain: "FWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Silver Ice Metallic",
    mpg: "26 city / 32 hwy",
    image: PEX(16180485),
  },
  {
    id: "bcc-2022-kia-forte",
    year: 2022,
    make: "Kia",
    model: "Forte",
    trim: "LXS",
    price: 17900,
    mileage: 28700,
    bodyStyle: "Sedan",
    drivetrain: "FWD",
    transmission: "CVT",
    fuel: "Gasoline",
    exteriorColor: "Deep Sea Blue",
    mpg: "29 city / 39 hwy",
    image: PEX(17539741),
    tag: "Low Miles",
  },
  {
    id: "bcc-2020-hyundai-sonata",
    year: 2020,
    make: "Hyundai",
    model: "Sonata",
    trim: "SEL",
    price: 18400,
    mileage: 44500,
    bodyStyle: "Sedan",
    drivetrain: "FWD",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Quartz White Pearl",
    mpg: "28 city / 38 hwy",
    image: PEX(100656),
  },
  {
    id: "bcc-2017-honda-fit",
    year: 2017,
    make: "Honda",
    model: "Fit",
    trim: "EX",
    price: 12900,
    mileage: 79800,
    bodyStyle: "Hatchback",
    drivetrain: "FWD",
    transmission: "CVT",
    fuel: "Gasoline",
    exteriorColor: "Aegean Blue Metallic",
    mpg: "33 city / 40 hwy",
    image: PEX(17078606),
  },
  {
    id: "bcc-2019-vw-jetta",
    year: 2019,
    make: "Volkswagen",
    model: "Jetta",
    trim: "S",
    price: 14900,
    mileage: 66200,
    bodyStyle: "Sedan",
    drivetrain: "FWD",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Pure White",
    mpg: "30 city / 40 hwy",
    image: PEX(14764071),
    tag: "Price Drop",
  },
  {
    id: "bcc-2021-toyota-tacoma",
    year: 2021,
    make: "Toyota",
    model: "Tacoma",
    trim: "SR5 V6 4x4",
    price: 33900,
    mileage: 38400,
    bodyStyle: "Truck",
    drivetrain: "4WD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Cement Gray",
    mpg: "18 city / 22 hwy",
    image: PEX(1015555),
  },
  {
    id: "bcc-2018-ram-1500",
    year: 2018,
    make: "Ram",
    model: "1500",
    trim: "Big Horn 4x4",
    price: 24900,
    mileage: 84700,
    bodyStyle: "Truck",
    drivetrain: "4WD",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Bright White",
    mpg: "17 city / 25 hwy",
    image: PEX(15643000),
  },
  {
    id: "bcc-2020-subaru-outback",
    year: 2020,
    make: "Subaru",
    model: "Outback",
    trim: "Premium AWD",
    price: 25900,
    mileage: 46900,
    bodyStyle: "SUV",
    drivetrain: "AWD",
    transmission: "CVT",
    fuel: "Gasoline",
    exteriorColor: "Ice Silver Metallic",
    mpg: "26 city / 33 hwy",
    image: PEX(12770250),
  },
  {
    id: "bcc-2019-mazda3-hatch",
    year: 2019,
    make: "Mazda",
    model: "Mazda3",
    trim: "Preferred Hatchback",
    price: 17400,
    mileage: 51600,
    bodyStyle: "Hatchback",
    drivetrain: "FWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Machine Gray Metallic",
    mpg: "26 city / 35 hwy",
    image: PEX(27138933),
  },
  {
    id: "bcc-2016-lexus-es350",
    year: 2016,
    make: "Lexus",
    model: "ES 350",
    trim: "Base",
    price: 17900,
    mileage: 92300,
    bodyStyle: "Sedan",
    drivetrain: "FWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Nebula Gray Pearl",
    mpg: "21 city / 31 hwy",
    image: PEX(11501948),
    luxury: true,
  },
  {
    id: "bcc-2022-honda-civic",
    year: 2022,
    make: "Honda",
    model: "Civic",
    trim: "LX",
    price: 20900,
    mileage: 24100,
    bodyStyle: "Sedan",
    drivetrain: "FWD",
    transmission: "CVT",
    fuel: "Gasoline",
    exteriorColor: "Sonic Gray Pearl",
    mpg: "31 city / 40 hwy",
    image: PEX(21821470),
    tag: "New Arrival",
  },

  /* ------------------------------------------------------------------ *
   * DEMO / PLACEHOLDER INVENTORY — not real dealership stock.
   * Added so the eight newer category landing pages (minivans, cargo &
   * passenger vans, commercial, former police, convertibles, wagons,
   * luxury) show results before a live feed is connected. Photos are
   * real, licensed Pexels/Unsplash stock, sourced the same way as above.
   * ------------------------------------------------------------------ */

  // --- Minivans ---
  {
    id: "bcc-2019-chrysler-pacifica",
    year: 2019,
    make: "Chrysler",
    model: "Pacifica",
    trim: "Touring L",
    price: 22900,
    mileage: 58400,
    bodyStyle: "Minivan",
    drivetrain: "FWD",
    transmission: "9-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Bright White",
    mpg: "19 city / 28 hwy",
    image: PEX(20512070),
  },
  {
    id: "bcc-2020-toyota-sienna",
    year: 2020,
    make: "Toyota",
    model: "Sienna",
    trim: "XLE AWD",
    price: 28500,
    mileage: 44100,
    bodyStyle: "Minivan",
    drivetrain: "AWD",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Blizzard Pearl",
    mpg: "18 city / 24 hwy",
    image: PEX(37098546),
    tag: "Low Miles",
  },
  {
    id: "bcc-2019-honda-odyssey",
    year: 2019,
    make: "Honda",
    model: "Odyssey",
    trim: "EX-L",
    price: 25400,
    mileage: 52600,
    bodyStyle: "Minivan",
    drivetrain: "FWD",
    transmission: "9-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Modern Steel Metallic",
    mpg: "19 city / 28 hwy",
    image: PEX(12960352),
  },

  // --- Cargo Vans (also commercial) ---
  {
    id: "bcc-2019-ford-transit-250-cargo",
    year: 2019,
    make: "Ford",
    model: "Transit 250",
    trim: "Cargo Medium Roof",
    price: 26900,
    mileage: 68300,
    bodyStyle: "Cargo Van",
    drivetrain: "RWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Oxford White",
    mpg: "15 city / 19 hwy",
    image: PEX(11446697),
    commercial: true,
  },
  {
    id: "bcc-2020-ram-promaster-1500-cargo",
    year: 2020,
    make: "Ram",
    model: "ProMaster 1500",
    trim: "Low Roof 136\" WB",
    price: 25900,
    mileage: 41800,
    bodyStyle: "Cargo Van",
    drivetrain: "FWD",
    transmission: "9-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Bright White",
    mpg: "17 city / 23 hwy",
    image: PEX(32976307),
    commercial: true,
    tag: "Low Miles",
  },
  {
    id: "bcc-2018-mercedes-sprinter-2500-cargo",
    year: 2018,
    make: "Mercedes-Benz",
    model: "Sprinter 2500",
    trim: "Cargo 144\" WB",
    price: 28900,
    mileage: 73200,
    bodyStyle: "Cargo Van",
    drivetrain: "RWD",
    transmission: "7-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Arctic White",
    mpg: "18 city / 22 hwy",
    image: PEX(4620555),
    commercial: true,
  },

  // --- Passenger Vans (also commercial) ---
  {
    id: "bcc-2019-ford-e350-passenger",
    year: 2019,
    make: "Ford",
    model: "E-350 Super Duty",
    trim: "XLT 12-Passenger",
    price: 29400,
    mileage: 71500,
    bodyStyle: "Passenger Van",
    drivetrain: "RWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Oxford White",
    mpg: "12 city / 16 hwy",
    image: PEX(35831379),
    commercial: true,
  },
  {
    id: "bcc-2017-chevrolet-express-3500-passenger",
    year: 2017,
    make: "Chevrolet",
    model: "Express 3500",
    trim: "LT 15-Passenger",
    price: 21900,
    mileage: 96700,
    bodyStyle: "Passenger Van",
    drivetrain: "RWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Summit White",
    mpg: "11 city / 16 hwy",
    image: PEX(27001152),
    commercial: true,
  },

  // --- Commercial: work truck ---
  {
    id: "bcc-2018-ford-f250-super-duty",
    year: 2018,
    make: "Ford",
    model: "F-250 Super Duty",
    trim: "XL Regular Cab",
    price: 27900,
    mileage: 82400,
    bodyStyle: "Truck",
    drivetrain: "4WD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Oxford White",
    mpg: "13 city / 17 hwy",
    image: IMG("photo-1605893477799-b99e3b8b93fe"),
    commercial: true,
  },

  // --- Former police / fleet (all Sedan) ---
  {
    id: "bcc-2018-ford-police-interceptor-sedan",
    year: 2018,
    make: "Ford",
    model: "Police Interceptor Sedan",
    trim: "AWD",
    price: 15900,
    mileage: 92400,
    bodyStyle: "Sedan",
    drivetrain: "AWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Oxford White",
    mpg: "16 city / 24 hwy",
    image: PEX(5880087),
    formerPolice: true,
  },
  {
    id: "bcc-2017-ford-police-interceptor-sedan",
    year: 2017,
    make: "Ford",
    model: "Police Interceptor Sedan",
    trim: "AWD",
    price: 13900,
    mileage: 108700,
    bodyStyle: "Sedan",
    drivetrain: "AWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Black",
    mpg: "16 city / 24 hwy",
    image: PEX(11251655),
    formerPolice: true,
  },
  {
    id: "bcc-2016-ford-police-interceptor-sedan",
    year: 2016,
    make: "Ford",
    model: "Police Interceptor Sedan",
    trim: "FWD",
    price: 11900,
    mileage: 131200,
    bodyStyle: "Sedan",
    drivetrain: "FWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Silver",
    mpg: "18 city / 26 hwy",
    image: PEX(9161093),
    formerPolice: true,
    tag: "Price Drop",
  },

  // --- Convertibles ---
  {
    id: "bcc-2019-ford-mustang-convertible",
    year: 2019,
    make: "Ford",
    model: "Mustang",
    trim: "EcoBoost Premium Convertible",
    price: 27900,
    mileage: 33100,
    bodyStyle: "Convertible",
    drivetrain: "RWD",
    transmission: "10-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Oxford White",
    mpg: "21 city / 31 hwy",
    image: PEX(33383462),
    tag: "Low Miles",
  },
  {
    id: "bcc-2017-mercedes-sl450-roadster",
    year: 2017,
    make: "Mercedes-Benz",
    model: "SL 450",
    trim: "Roadster",
    price: 38900,
    mileage: 39400,
    bodyStyle: "Convertible",
    drivetrain: "RWD",
    transmission: "9-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Obsidian Black Metallic",
    mpg: "20 city / 28 hwy",
    image: PEX(205738),
    luxury: true,
  },
  {
    id: "bcc-2018-mercedes-s560-cabriolet",
    year: 2018,
    make: "Mercedes-Benz",
    model: "S 560",
    trim: "Cabriolet",
    price: 52900,
    mileage: 27600,
    bodyStyle: "Convertible",
    drivetrain: "RWD",
    transmission: "9-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Designo Diamond White",
    mpg: "17 city / 26 hwy",
    image: PEX(16716063),
    luxury: true,
    tag: "Low Miles",
  },

  // --- Wagons ---
  {
    id: "bcc-2019-vw-golf-sportwagen",
    year: 2019,
    make: "Volkswagen",
    model: "Golf SportWagen",
    trim: "SE",
    price: 18900,
    mileage: 41700,
    bodyStyle: "Wagon",
    drivetrain: "FWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Silk Blue Metallic",
    mpg: "25 city / 33 hwy",
    image: PEX(16531727),
    tag: "Low Miles",
  },
  {
    id: "bcc-2018-mercedes-e400-wagon",
    year: 2018,
    make: "Mercedes-Benz",
    model: "E 400",
    trim: "4MATIC Wagon",
    price: 33900,
    mileage: 46200,
    bodyStyle: "Wagon",
    drivetrain: "AWD",
    transmission: "9-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Polar White",
    mpg: "20 city / 26 hwy",
    image: PEX(18837778),
    luxury: true,
  },

  // --- Luxury (dedicated) ---
  {
    id: "bcc-2019-bmw-750i-xdrive",
    year: 2019,
    make: "BMW",
    model: "750i",
    trim: "xDrive",
    price: 34900,
    mileage: 43800,
    bodyStyle: "Sedan",
    drivetrain: "AWD",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Carbon Black Metallic",
    mpg: "16 city / 25 hwy",
    image: PEX(27659273),
    luxury: true,
  },
  {
    id: "bcc-2018-audi-a4-premium-plus",
    year: 2018,
    make: "Audi",
    model: "A4",
    trim: "Premium Plus quattro",
    price: 22900,
    mileage: 51200,
    bodyStyle: "Sedan",
    drivetrain: "AWD",
    transmission: "7-Speed S tronic",
    fuel: "Gasoline",
    exteriorColor: "Brilliant Black",
    mpg: "24 city / 31 hwy",
    image: PEX(16288341),
    luxury: true,
  },

  // --- Coupe + Hybrid: added so all 15 category pages have stock ---
  {
    id: "bcc-2019-bmw-430i-coupe",
    year: 2019,
    make: "BMW",
    model: "430i",
    trim: "Coupe",
    price: 24900,
    mileage: 45600,
    bodyStyle: "Coupe",
    drivetrain: "RWD",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
    exteriorColor: "Alpine White",
    mpg: "23 city / 34 hwy",
    image: IMG("photo-1546614042-7df3c24c9e5d"),
    luxury: true,
  },
  {
    id: "bcc-2019-toyota-camry-hybrid",
    year: 2019,
    make: "Toyota",
    model: "Camry",
    trim: "Hybrid SE",
    price: 23900,
    mileage: 47800,
    bodyStyle: "Sedan",
    drivetrain: "FWD",
    transmission: "CVT",
    fuel: "Hybrid",
    exteriorColor: "Celestial Silver Metallic",
    mpg: "44 city / 47 hwy",
    image: IMG("photo-1621007947382-bb3c3994e3fb"),
    tag: "Certified",
  },
];

/** The homepage "featured" strip shows just the first dozen. */
export const FEATURED_VEHICLES = VEHICLES.slice(0, 12);

export const PRICE_RANGES = [
  { label: "Any price", min: 0, max: Infinity },
  { label: "Under $15,000", min: 0, max: 15000 },
  { label: "$15,000 – $20,000", min: 15000, max: 20000 },
  { label: "$20,000 – $25,000", min: 20000, max: 25000 },
  { label: "$25,000 – $35,000", min: 25000, max: 35000 },
  { label: "$35,000+", min: 35000, max: Infinity },
] as const;

export const MILEAGE_RANGES = [
  { label: "Any mileage", min: 0, max: Infinity },
  { label: "Under 30,000 mi", min: 0, max: 30000 },
  { label: "30,000 – 60,000 mi", min: 30000, max: 60000 },
  { label: "60,000 – 90,000 mi", min: 60000, max: 90000 },
  { label: "Over 90,000 mi", min: 90000, max: Infinity },
] as const;

export const INVENTORY_SORTS = [
  { value: "year-desc", label: "Newest first" },
  { value: "price-asc", label: "Price: Low to High" },
  { value: "price-desc", label: "Price: High to Low" },
  { value: "mileage-asc", label: "Lowest mileage" },
] as const;

export type InventorySort = (typeof INVENTORY_SORTS)[number]["value"];

export const SORTS = [
  { value: "featured", label: "Featured" },
  { value: "price-asc", label: "Price: Low to High" },
  { value: "price-desc", label: "Price: High to Low" },
  { value: "year-desc", label: "Year: Newest" },
  { value: "mileage-asc", label: "Mileage: Lowest" },
] as const;

export type SortValue = (typeof SORTS)[number]["value"];

export const MAKES = Array.from(new Set(VEHICLES.map((v) => v.make))).sort();

export const YEARS = Array.from(new Set(VEHICLES.map((v) => v.year))).sort(
  (a, b) => b - a,
);

export const BODY_STYLES = Array.from(
  new Set(VEHICLES.map((v) => v.bodyStyle)),
).sort();

/** Canonical fuel types, so the filter offers all three even when a type has
 *  no vehicles in stock right now. */
export const FUEL_TYPES: Vehicle["fuel"][] = ["Gasoline", "Hybrid", "Electric"];

export function modelsForMake(make: string): string[] {
  const list = VEHICLES.filter((v) => make === "" || v.make === make).map(
    (v) => v.model,
  );
  return Array.from(new Set(list)).sort();
}

export const currency = (n: number) =>
  n.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  });

export const miles = (n: number) => `${n.toLocaleString("en-US")} mi`;

/** Rough monthly estimate — 72 mo, 7.5% APR, 10% down. Illustration only. */
export function estMonthly(price: number): number {
  const principal = price * 0.9;
  const r = 0.075 / 12;
  const n = 72;
  const m = (principal * r) / (1 - Math.pow(1 + r, -n));
  return Math.round(m / 5) * 5;
}
