export type Review = {
  id: string;
  name: string;
  initials: string;
  date: string; // ISO
  rating: 1 | 2 | 3 | 4 | 5;
  dept: "Sales" | "Service" | "Financing";
  vehicle?: string;
  text: string;
  response?: string;
};

/** Overall distribution shown in the breakdown bars (all reviews, not just the
 * recent ones listed below). Totals to REVIEW_TOTAL. */
export const DISTRIBUTION: Record<5 | 4 | 3 | 2 | 1, number> = {
  5: 548,
  4: 41,
  3: 15,
  2: 5,
  1: 3,
};
export const REVIEW_TOTAL = Object.values(DISTRIBUTION).reduce((a, b) => a + b, 0);
export const REVIEW_AVG =
  Math.round(
    (Object.entries(DISTRIBUTION).reduce(
      (sum, [k, n]) => sum + Number(k) * n,
      0,
    ) /
      REVIEW_TOTAL) *
      10,
  ) / 10;

export const THEMES: { label: string; keyword: string; count: number }[] = [
  { label: "No pressure", keyword: "pressure", count: 61 },
  { label: "Fair price", keyword: "price", count: 47 },
  { label: "Honest about the car", keyword: "honest", count: 39 },
  { label: "Financing help", keyword: "financ", count: 33 },
  { label: "Quick paperwork", keyword: "paperwork", count: 24 },
  { label: "Service department", keyword: "service", count: 22 },
  { label: "Would come back", keyword: "again", count: 58 },
  { label: "Trade-in", keyword: "trade", count: 19 },
];

export const FEATURED: Review = {
  id: "r-featured",
  name: "Marisol D.",
  initials: "MD",
  date: "2026-06-14",
  rating: 5,
  dept: "Sales",
  vehicle: "2019 Honda CR-V",
  text: "I put off replacing my car for two years because I dreaded the dealership part of it. My brother-in-law told me to just go see the people at Bergen. The price on the window was the price I paid — I kept waiting for the fees to show up and they never did. They pointed out a scratch on the bumper I hadn't even noticed and knocked a little off for it. Financing was done before I got there because I'd filled out the form online. I was in and out in about an hour with a car I actually like. I've since sent my mom and a coworker, and both had the same experience. This is how it should work everywhere.",
};

export const REVIEWS: Review[] = [
  {
    id: "r1",
    name: "Kevin R.",
    initials: "KR",
    date: "2026-07-02",
    rating: 5,
    dept: "Sales",
    vehicle: "2020 Toyota Camry",
    text: "Bought a Camry for my daughter's first car. Nobody pushed an extended warranty or paint protection on us. They let her take her time on the test drive and answered her questions directly. Straightforward from start to finish.",
  },
  {
    id: "r2",
    name: "Aisha T.",
    initials: "AT",
    date: "2026-06-28",
    rating: 5,
    dept: "Financing",
    vehicle: "2019 Hyundai Elantra",
    text: "My credit isn't great and I was braced for a hard sell on a bad rate. Denise walked me through three options, explained what each one meant for my monthly payment, and got me a credit union rate I didn't think I'd qualify for. No games.",
  },
  {
    id: "r3",
    name: "Frank P.",
    initials: "FP",
    date: "2026-06-20",
    rating: 5,
    dept: "Sales",
    vehicle: "2021 Toyota 4Runner",
    text: "Third vehicle we've bought here over the years. Same honest people every time. Their service shop has done all the maintenance on the other two and never once tried to sell us work we didn't need.",
  },
  {
    id: "r4",
    name: "Denise A.",
    initials: "DA",
    date: "2026-06-11",
    rating: 4,
    dept: "Sales",
    vehicle: "2018 Ford Escape",
    text: "Good experience overall and a fair price. Only reason it's four stars and not five is the car wasn't detailed as well as I'd have liked when I picked it up — a few smudges on the inside of the windshield. They offered to redo it but I was in a hurry. Would still buy here again.",
    response:
      "Thanks Denise, and sorry the detail wasn't up to par that day. We've talked it through with the crew. Bring it by any time and we'll get the glass sorted, no charge.",
  },
  {
    id: "r5",
    name: "Marcus B.",
    initials: "MB",
    date: "2026-06-05",
    rating: 5,
    dept: "Service",
    text: "Took my truck in for brakes expecting the usual upsell. They measured the pads, showed me the number, and told me the rears could wait another 6 months. Did just the fronts. Out the door for less than I expected.",
  },
  {
    id: "r6",
    name: "Sophia L.",
    initials: "SL",
    date: "2026-05-30",
    rating: 5,
    dept: "Sales",
    vehicle: "2020 Mazda CX-5",
    text: "First time buying from a used lot instead of a franchise dealer and I was nervous about it. The inspection report they handed me was thorough and they didn't gloss over the two small things it flagged. Felt like they wanted me to know exactly what I was getting.",
  },
  {
    id: "r7",
    name: "Ray C.",
    initials: "RC",
    date: "2026-05-22",
    rating: 5,
    dept: "Financing",
    vehicle: "2017 Ford F-150",
    text: "Rolled my old loan's shortfall into the new one and they showed me on paper exactly how that changed the payment before I signed anything. No surprises at the desk.",
  },
  {
    id: "r8",
    name: "Nina K.",
    initials: "NK",
    date: "2026-05-14",
    rating: 3,
    dept: "Sales",
    vehicle: "2016 Toyota Highlander",
    text: "The buying process itself was fine and low pressure. Docked two stars because the check-engine light came on a week after I drove off. To their credit, they had me bring it in and covered the sensor under the warranty without any argument. Ended okay but it was a stressful week.",
    response:
      "Nina, that's a fair three stars — a light coming on that soon is exactly what nobody wants. Glad the warranty did its job. We've added that sensor check to our pre-sale list so it doesn't happen to the next person.",
  },
  {
    id: "r9",
    name: "Diego M.",
    initials: "DM",
    date: "2026-05-08",
    rating: 5,
    dept: "Sales",
    vehicle: "2019 Tesla Model 3",
    text: "Priced a few hundred under what I'd seen the same year and mileage going for elsewhere. They were upfront that the range isn't what it was new. Appreciated not being told a fairy tale about the battery.",
  },
  {
    id: "r10",
    name: "Carol W.",
    initials: "CW",
    date: "2026-04-29",
    rating: 5,
    dept: "Service",
    text: "I don't know much about cars and I've been talked into things before. Rich explained what the noise actually was, showed me the worn part, and it was a $40 fix. Honest shop.",
  },
  {
    id: "r11",
    name: "Tomás R.",
    initials: "TR",
    date: "2026-04-21",
    rating: 5,
    dept: "Sales",
    vehicle: "2020 Subaru Outback",
    text: "Drove down from Rockland after a bad experience at two other lots. Night and day. They let me put a deposit to hold it for a day while I arranged my own financing, and refunded it the second I asked to switch to theirs because the rate was better.",
  },
  {
    id: "r12",
    name: "Priya S.",
    initials: "PS",
    date: "2026-04-15",
    rating: 5,
    dept: "Financing",
    vehicle: "2022 Kia Forte",
    text: "First car on my own credit. They didn't make me feel dumb for asking what APR meant. Explained every line of the contract twice because I asked them to.",
  },
  {
    id: "r13",
    name: "Walter J.",
    initials: "WJ",
    date: "2026-04-06",
    rating: 4,
    dept: "Sales",
    vehicle: "2018 Chevrolet Equinox",
    text: "Fair deal and no pressure. The wait to finish the paperwork was longer than I'd hoped on a Saturday — about 90 minutes. Everything else was smooth and the car's been great for three months now.",
  },
  {
    id: "r14",
    name: "Amara O.",
    initials: "AO",
    date: "2026-03-28",
    rating: 5,
    dept: "Sales",
    vehicle: "2021 Honda Civic",
    text: "They talked me OUT of a more expensive car because they didn't think it fit what I described needing it for. Pointed me to the Civic instead and I've been thrilled with it. Who does that?",
  },
  {
    id: "r15",
    name: "Greg H.",
    initials: "GH",
    date: "2026-03-19",
    rating: 5,
    dept: "Service",
    text: "Bought the car elsewhere years ago but they still service it like it's one of theirs. Called before doing anything that wasn't on my list. That's all I want from a shop.",
  },
  {
    id: "r16",
    name: "Lena F.",
    initials: "LF",
    date: "2026-03-10",
    rating: 5,
    dept: "Sales",
    vehicle: "2019 Nissan Altima",
    text: "Sold them my old car outright — didn't buy anything from them. The offer matched the estimate they'd emailed, and I had a check in about 40 minutes. No pressure to look at their lot on the way out.",
  },
  {
    id: "r17",
    name: "Omar B.",
    initials: "OB",
    date: "2026-03-02",
    rating: 5,
    dept: "Financing",
    vehicle: "2020 Ford Expedition",
    text: "Big family, needed a big car, not a big budget. They found a lender that worked and were honest that the payment would be tight — didn't just tell me what I wanted to hear.",
  },
  {
    id: "r18",
    name: "Janet M.",
    initials: "JM",
    date: "2026-02-22",
    rating: 5,
    dept: "Sales",
    vehicle: "2018 BMW 530i",
    text: "Nervous about a used German car and the maintenance costs. They were candid about what to budget for and even printed out the service history. Bought it anyway, eyes open, no regrets.",
  },
  {
    id: "r19",
    name: "Chris D.",
    initials: "CD",
    date: "2026-02-13",
    rating: 5,
    dept: "Sales",
    vehicle: "2017 Nissan Juke",
    text: "Needed the cheapest reliable thing on the lot. They didn't treat me like a lesser customer for it. Inspected, warrantied, and it's started every morning since.",
  },
  {
    id: "r20",
    name: "Bianca T.",
    initials: "BT",
    date: "2026-02-04",
    rating: 4,
    dept: "Service",
    text: "Solid work and fair price on a timing-belt job. Half a star off because they had it a day longer than quoted waiting on a part — but they called to tell me rather than leaving me wondering.",
  },
  {
    id: "r21",
    name: "Hector V.",
    initials: "HV",
    date: "2026-01-27",
    rating: 5,
    dept: "Sales",
    vehicle: "2021 Toyota Tacoma",
    text: "Low-mileage Tacoma, priced right for what it was. They didn't pretend it was a steal — just a fair price on a good truck. Refreshing.",
  },
  {
    id: "r22",
    name: "Yuki N.",
    initials: "YN",
    date: "2026-01-18",
    rating: 5,
    dept: "Financing",
    vehicle: "2019 Mazda3",
    text: "Pre-qualified online, real number came back in about ten minutes, and it held up in person. No bait and switch on the rate.",
  },
  {
    id: "r23",
    name: "Sal G.",
    initials: "SG",
    date: "2026-01-09",
    rating: 5,
    dept: "Sales",
    vehicle: "2020 Honda CR-V",
    text: "Family-run and it shows. Gina remembered my kids' names from a visit six months earlier when I came back to actually buy. Small thing, but it tells you what kind of place it is.",
  },
  {
    id: "r24",
    name: "Renata P.",
    initials: "RP",
    date: "2025-12-29",
    rating: 5,
    dept: "Sales",
    vehicle: "2018 Toyota Corolla",
    text: "Bought a Corolla for my son at college. The price had actually dropped since I first looked, and they honored the lower number without me having to ask. Would come back.",
  },
  {
    id: "r25",
    name: "Andre L.",
    initials: "AL",
    date: "2025-12-18",
    rating: 5,
    dept: "Service",
    text: "NJ inspection prep. They checked it over, told me it would pass as-is, and didn't invent a reason to charge me more. In and out in 25 minutes.",
  },
  {
    id: "r26",
    name: "Meghan C.",
    initials: "MC",
    date: "2025-12-06",
    rating: 5,
    dept: "Sales",
    vehicle: "2019 Hyundai Elantra GT",
    text: "Second car from Bergen. The hatchback I wanted wasn't on the lot, so they took my info and called two weeks later when one came in. Never felt like I was being worked.",
  },
];
